"""add original_filename to documents

Revision ID: 0b18da6ec898
Revises: bb703a78a45a
Create Date: 2026-08-30 14:17:23.182324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b18da6ec898'
down_revision: Union[str, None] = 'bb703a78a45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
