"""add ai_analysis column

Revision ID: 1588c61f0257
Revises: 6a0def98de75
Create Date: 2026-09-03 23:34:06.006877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1588c61f0257'
down_revision: Union[str, None] = '6a0def98de75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'ai_analysis')
    # ### end Alembic commands ###
