"""restore original_filename

Revision ID: 2ab93ffb5fc5
Revises: 1588c61f0257
Create Date: 2026-09-04 06:48:21.706594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab93ffb5fc5'
down_revision: Union[str, None] = '1588c61f0257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
