"""add AIAnalysis, Flag, AuditEvent, PIIMapping, Precedent, Notification

Revision ID: d35155d3eae6
Revises: c2ae13239a4b
Create Date: 2026-09-02 23:29:27.660763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd35155d3eae6'
down_revision: Union[str, None] = 'c2ae13239a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ready', 'error', name='analysisstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('submitted', 'viewed', 'decided', 'resubmitted', name='auditaction'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pii_mappings',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('placeholder', sa.String(), nullable=False),
    sa.Column('original_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'placeholder')
    )
    op.create_table('precedents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('masked_text', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('passage_excerpt', sa.String(), nullable=False),
    sa.Column('matched_rule_id', sa.UUID(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ),
    sa.ForeignKeyConstraint(['matched_rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("REVOKE UPDATE, DELETE ON audit_events FROM compliance")
    op.add_column('documents', sa.Column('thread_root_id', sa.UUID(), nullable=True))
    op.alter_column('documents', 'original_filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'documents', 'documents', ['thread_root_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'original_filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('documents', 'thread_root_id')
    op.drop_table('flags')
    op.drop_table('precedents')
    op.drop_table('pii_mappings')
    op.drop_table('notifications')
    op.drop_table('audit_events')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
