"""add model name and error message to AI analysis

Revision ID: d4285f7785dc
Revises: e4afc062d6c3
Create Date: 2026-09-09 16:19:19.052297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4285f7785dc'
down_revision: Union[str, None] = 'e4afc062d6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analyses', sa.Column('model_name', sa.String(), nullable=True))
    op.add_column('ai_analyses', sa.Column('error_message', sa.String(), nullable=True))
    op.alter_column('precedents', 'decision',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('approve', 'reject', 'needs_revision', name='decision'),
               postgresql_using='decision::text::decision',
               existing_nullable=False)
    op.alter_column('precedents', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('precedents', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('precedents', 'decision',
               existing_type=sa.Enum('approve', 'reject', 'needs_revision', name='decision'),
               type_=sa.VARCHAR(),
               postgresql_using='decision::text',
               existing_nullable=False)
    op.drop_column('ai_analyses', 'error_message')
    op.drop_column('ai_analyses', 'model_name')
    # ### end Alembic commands ###
